### ISSUE TITLE
Unsupported major.minor version 55.0

### ISSUE THREAD

**Issue by BartoszCoyote** [mariuszs/groovy-spring-boot#1]
Chyba któryś plugin nie obsługuje javy 11.

Taki error dostaje podczas odpalania spring boota z intellij i z konsoli. 

`Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 55.0`

**Comment by mariuszs** [comment]
sprawdź czy na pewno korzystasz z Javy 11

    ./mvnw --version

bo wygląda że wszystko jest OK

https://travis-ci.org/mariuszs/jmod-spring-boot

**Comment by BartoszCoyote** [comment]
Właśnie gdy uruchamiam używając mavena to działa poprawnie, nie działa podczas odpalania głownej klasy springa.

**Comment by mariuszs** [comment]
Błąd który masz sugeruje że nie odpalasz aplikacji w Javie 11 w Idei. Natomiast żeby dało się ją odpalić to musisz najpierw dodać do VM options następujący wpis:

    --add-opens java.base/java.lang=spring.core

![Run Application Configuration](http://pix.toile-libre.org/upload/original/1537461599.png)

Niżej będzie informacja o wersji Javy na której to odpalasz (JRE).
